  
Resources:
  LeekoMessageTemplateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: LeekoMessageTemplate
      AttributeDefinitions:
        - AttributeName: templateId
          AttributeType: S
      KeySchema:
        - AttributeName: templateId
          KeyType: HASH

  LeekoMessageMapping:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: LeekoMessageMapping
      AttributeDefinitions:
        - AttributeName: recipientId
          AttributeType: S
        - AttributeName: templateId
          AttributeType: S
      KeySchema:
        - AttributeName: recipientId
          KeyType: HASH
        - AttributeName: templateId
          KeyType: RANGE